In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Dropout
from keras.layers import LSTM
from keras.utils import np_utils

H:\Anaconda\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
#Reading the data and converting it into lower case
data = open("Othello.txt").read().lower()
#Now we will sort the data which is obtained in the form of list
chars = sorted(list(set(data)))
#Now we are counting the total number of characters
totalChars = len(data)
#Number of unique chars
numberOfUniqueChars = len(chars)

In [3]:
#For better results we are assigning Id to each character
CharsForids = {char:Id for Id, char in enumerate(chars)}

#This is the opposite to the above
idsForChars = {Id:char for Id, char in enumerate(chars)}

#Here we are deciding the number of characters learned i.e. Timestep
numberOfCharsToLearn = 100

In [4]:
#Since our timestep sequence represetns a process for every 100 chars we omit
#the first 100 chars so the loop runs a 100 less or there will be index out of
#range
counter = totalChars - numberOfCharsToLearn

In [5]:
#Here we are storing the input data
charX = []
#Here we have stored the output data
y = []
#This loops through all the characters in the data skipping the first 100
for i in range(0, counter, 1):
    #This one goes from 0-100 so it gets 100 values starting from 0 and stops
    #just before the 100th value
    theInputChars = data[i:i+numberOfCharsToLearn]
    #If we do not use ':' we start with 0, and so we get the actual 100th value
    #Essentially, the output Chars is the next char in line for those 100 chars
    #in X
    theOutputChars = data[i + numberOfCharsToLearn]
    #Through this we are adding/appending 100 chars as an Id to list charX
    charX.append([CharsForids[char] for char in theInputChars])
    #For every 100 values there is one y value which is the output
    y.append(CharsForids[theOutputChars])

In [6]:
#Len charX represents how many of those time steps we have
#Our features are set to 1 because in the output we are only predicting 1 char
#Finally numberOfCharsToLearn is how many character we process
X = np.reshape(charX, (len(charX), numberOfCharsToLearn, 1))

In [7]:
#For normalizing
X = X/float(numberOfUniqueChars)

#This sets it up for us so we can have a categorical(#feature) output format
y = np_utils.to_categorical(y)
print(y)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
model = Sequential()
#Since we know the shape of our Data we can input the timestep and feature data
#The number of timestep sequence are dealt with in the fit function
model.add(LSTM(256, input_shape=(X.shape[1], X.shape[2])))
model.add(Dropout(0.2))
#number of features on the output
model.add(Dense(y.shape[1], activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam')
model.fit(X, y, epochs=100, batch_size=128)
model.save_weights("Othello.hdf5")
model.load_weights("Othello.hdf5")


Epoch 1/100
1760/1760 [==============================] - 15s 9ms/step - loss: 3.2341
Epoch 2/100
1760/1760 [==============================] - 11s 6ms/step - loss: 3.0246
Epoch 3/100
1760/1760 [==============================] - 10s 6ms/step - loss: 3.0049
Epoch 4/100
1760/1760 [==============================] - 10s 6ms/step - loss: 3.0015
Epoch 5/100
1760/1760 [==============================] - 10s 6ms/step - loss: 2.9964
Epoch 6/100
1760/1760 [==============================] - 10s 6ms/step - loss: 2.9952
Epoch 7/100
1760/1760 [==============================] - 10s 6ms/step - loss: 2.9937
Epoch 8/100
1760/1760 [==============================] - 10s 6ms/step - loss: 2.9909
Epoch 9/100
1760/1760 [==============================] - 10s 6ms/step - loss: 2.9940
Epoch 10/100
1760/1760 [==============================] - 10s 6ms/step - loss: 2.9912
Epoch 11/100
1760/1760 [==============================] - 10s 6ms/step - loss: 2.9896
Epoch 12/100
1760/1760 [==============================] - 10s 6

1760/1760 [==============================] - 10s 6ms/step - loss: 1.5714
Epoch 97/100
1760/1760 [==============================] - 10s 6ms/step - loss: 1.4938
Epoch 98/100
1760/1760 [==============================] - 10s 6ms/step - loss: 1.4075
Epoch 99/100
1760/1760 [==============================] - 10s 6ms/step - loss: 1.4013
Epoch 100/100
1760/1760 [==============================] - 10s 6ms/step - loss: 1.3536


In [9]:
randomVal = np.random.randint(0, len(charX)-1)
randomStart = charX[randomVal]
for i in range(500):
    x = np.reshape(randomStart, (1, len(randomStart), 1))
    x = x/float(numberOfUniqueChars)
    pred = model.predict(x)
    index = np.argmax(pred)
    randomStart.append(index)
    randomStart = randomStart[1: len(randomStart)]
print("".join([idsForChars[value] for value in randomStart]))

 des woetei 
thi had soe cam mored ser thet i she dademe thet h s a apee pat the  ide btt th t l  ih
